#!/bin/sh

function __readlink_f {
    local target=$1
    local name=

    while [ "$target" != "" ]; do
        cd $(dirname "$target")
        name=$(basename "$target")
        target=$(readlink "$name")
    done
    echo "$(pwd -P)/${name}"
}

SCRIPT_PATH=$(__readlink_f "$0")
SCRIPT_DIR=$(dirname "${SCRIPT_PATH}")

SRC_DIR="${SCRIPT_DIR}/src/main/scala"
SRC_PATH="${SRC_DIR}/Bench.scala"

set -e

# make source directory
mkdir -p "${SRC_DIR}"

# create scala source file
{
    echo "package easy_scala_bench"
    echo "class Bench {"
    echo "  @org.openjdk.jmh.annotations.Benchmark"
    echo "  def bench(): Unit = {"
    cat
    echo "  }"
    echo "}"
} > "${SRC_PATH}"

# run sbt-jmh
(cd "$SCRIPT_DIR" && sbt 'run -i 3 -wi 3 -f 1 -t 1 easy_scala_bench.Bench')

